### ISSUE TITLE
ranscription_editor_factbase dependency

### ISSUE THREAD

**Issue by DavidDoukhan** [pietrop/fact2_transcription_editor#1]
Dear Pietro,

I wanted to have a look to your transcription editor framework.

I tried to install transcription_editor_factbase, using the command line mentioned in your README
git clone git@github.com:frisch1/transcription_editor_factbase.git

However, it seems this repository is no more available.

Do you have any idea allowing to use your framework?

Regards,

**Comment by pietrop** [comment]
Hi David, 
Thanks for raising this issue, just I updated the README with the right command.  
(We changed repository when we open sourced)

```bash
git clone git@github.com:pietrop/fact2_transcription_editor.git
```

Let me know how you get on and if you have any further questions.

I'd also be curious to hear what's the main use case you are looking to use this for?

**Comment by DavidDoukhan** [comment]
Hi Petro,

Thanks for this quick answer!

I guess you may also change in the readme the following line:
`cd transcription_editor_factbase`
to 
`cd fact2_transcription_editor`

Concerning my use-case:
I'm looking for open-source transcription softwares (for now I'm mostly using transcriber), that may optionally interact with ASR systems, and display videos.
@hbredin suggested me to have a look at your project.

Thanks again!
